### ISSUE TITLE
4.2 PR not carried over to 4.3

### ISSUE THREAD

**Issue by klobuczek** [neo4j-drivers/testkit#155]
@robsdedude @bigmontz it looks like my changes from my PR https://github.com/neo4j-drivers/testkit/pull/58 disappeared in 4.3 which is ok for the driver/testkit directory, but every driver has its own exceptions in the tests but the `ruby` ones are not there anymore. If there is no better concept could you keep the ruby exceptions along the exceptions for other languages?

**Comment by robsdedude** [comment]
I think you just opened your PR after the creation of the 4.3 and https://github.com/neo4j-drivers/testkit/pull/58 was only opened to be merged into 4.2. So your changes were not deleted, but they were never introduced to the 4.3 branch. Feel free to open a PR that "forward-ports" https://github.com/neo4j-drivers/testkit/pull/58 to 4.3. 

Please also be aware that the 4.3 branch is still rapidly changing and we have no way of checking if our changes break tests for your driver. So I highly recommend that you fix your CI to a certain commit hash of testkit.
